import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {unifiedComparison} from './unifiedComparison.js';
import {selectRows,values} from './model.js';
const read=name=>JSON.parse(readFileSync(new URL(`../../data/${name}.json`,import.meta.url)));
test('combined columns conserve both House ledgers, NEP/API amounts and PAP controls',()=>{
 const stages=read('stage_trace_2027'),readings=read('house_reading_changes_2027');
 const combined=unifiedComparison(stages,readings);
 assert.equal(combined.projects.length,18124);
 assert.equal(combined.paps.length,46);
 const additions=selectRows(combined.projects,{readingStatus:'third_only'});
 assert.equal(additions.length,5);
 assert.equal(additions.reduce((sum,r)=>sum+r.reading_delta_php,0),134000000);
 assert(additions.every(r=>!r.second && r.third && !r.nep && !r.api));
 const grouped=combined.projects.filter(r=>r.reading_status==='repeated_key');
 assert.equal(grouped.length,1);assert.equal(grouped[0].second.amount_php,24000000);assert.equal(grouped[0].third.amount_php,24000000);
 const fap=combined.paps.find(r=>r.program==='Foreign-assisted projects');
 assert.deepEqual(values(fap,'paps'),[null,117749011000,44749011000,44749011000]);
 assert.equal(fap.reading_delta_php,0);assert.deepEqual(fap.third_pages,[939]);
 const changed=selectRows(combined.paps,{tab:'paps',readingStatus:'reading_changed',column:'reading_delta',direction:-1});
 assert.deepEqual(changed.map(r=>r.reading_delta_php),[68000000,66000000]);
 const absent=combined.paps.find(r=>r.label==='Replacement of Bridges (Temporary to Permanent)');
 assert.deepEqual(values(absent,'paps'),[200000000,200000000,null,null]);
 assert.equal(absent.reading_delta_php,null);
 const tampered=structuredClone(readings);
 tampered.projects[0].second.records[0].amount_php++;
 assert.throws(()=>unifiedComparison(stages,tampered),/anchor/);
});
