import { matchesSearch } from "../search.js";
import { matchesOffice, officeOptions, officeLabels } from "../../../viewers/project_offices.mjs";

export function mountHouseComparison(document, window, BudgetDisplay, D) {

'use strict';
const S=D.summary;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const php=BudgetDisplay.amount,bill=BudgetDisplay.amount,delta=BudgetDisplay.delta,cell=BudgetDisplay.cell;
const projectTable=$('projectRows').closest('table');
const hbLink=p=>p?`<a href="../HB_BUDGET/3%20-%20HB%2010858%20VOL%20IC.pdf#page=${Number(p)}" target="_blank" rel="noopener">House 2nd · I-C p.${Number(p)}</a>`:'House page not recorded';
const labels={exact_controls:'Exact peso agreement',within_tolerance:'Within 0.5% tolerance',control_difference:'Control difference',unmapped_control:'House control not mapped'};
$('built').textContent=`Built ${new Date(D.manifest.built_at).toLocaleString('en-GB',{timeZone:'Asia/Manila',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})} (Asia/Manila) · Source versions and SHA-256 hashes in the manifest`;
$('cards').innerHTML=[['NEP printed new appropriations',php(S.nep_printed_php),'Canonical source tree'],['House printed new appropriations',php(S.house_printed_php),'HB 10858 · Volume I-B p.9'],['Printed House − NEP',delta(S.printed_delta_php),'Same scope, all expense classes'],['House native I-C operations extract',php(S.house_extracted_php),`${S.house_allocations.toLocaleString()} allocations · ${S.house_balanced_paps}/${S.house_checked_paps} local PAPs balance`]].map(([k,v,n])=>`<div class="card ${k==='Printed House − NEP'?BudgetDisplay.deltaClass(S.printed_delta_php):''}"><span>${esc(k)}</span><strong>${esc(v)}</strong><small>${esc(n)}</small></div>`).join('');
$('budgetRows').innerHTML=[['New appropriations',S.nep_printed_php,S.house_printed_php],['Operations, including local/FAP',S.nep_operations_printed_php,S.house_operations_printed_php],['GAS + S2O, across expense classes',S.nep_gas_s2o_printed_php,S.house_gas_s2o_printed_php]].map(([k,n,h])=>`<tr><th scope="row">${k}</th>${cell(n)}${cell(h)}${cell(h-n,true)}</tr>`).join('');
$('programRows').innerHTML=D.programs.map(p=>`<tr><th scope="row">${esc(p.program)}</th>${[p.nep_local_control_php,p.house_local_control_php,p.house_local_control_php-p.nep_local_control_php,p.nep_fap_control_php,p.house_fap_extracted_php,p.house_local_extracted_php,p.api_coverage_php].map((x,i)=>cell(x,i===2)).join('')}</tr>`).join('');
$('apiText').textContent=`${S.api.api_rows.toLocaleString()} API rows total ${php(S.api.api_php)}. The ${php(S.nep_printed_php-S.api.api_php)} source/API difference reconciles as GAS/S2O ${php(S.nep_gas_s2o_printed_php)} + FAP ${php(S.nep_fap_php)} + ${S.api.unpaired_source_rows} non-FAP allocations totaling ${php(S.api.unpaired_source_php)}.`;
$('coverageSummary').innerHTML=`<p><strong>${S.house_balanced_paps}/${S.house_checked_paps} local PAP controls balance.</strong> The operations extract is ${php(S.house_extracted_php)}, versus printed operations ${php(S.house_operations_printed_php)}: an extraction difference of <strong>${php(S.house_operations_gap_php)}</strong>.</p><ul class="coverage-list"><li>Local PAP allocations: ${php(S.house_local_extracted_php)}.</li><li>${S.house_fap_projects} FAP projects: ${php(S.house_fap_php)}; project totals and funding splits balance.</li><li>Regional and office allocations remain distinct from named projects.</li><li>Personnel Services and GAS/S2O allocations are outside this operations comparison.</li></ul>`;
$('unresolvedRows').innerHTML=D.unresolved_paps.map(p=>`<tr><th scope="row">${esc(p.label)}</th>${cell(p.house_printed_php)}${cell(p.house_extracted_php)}${cell(p.coverage_difference_php,true)}<td>${p.house_pages.map(hbLink).join(' · ')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">All mapped native I-C PAP controls balance.</td></tr>';
$('repairs').innerHTML=D.house_repairs.map(r=>`<details><summary>${esc(r.reason||r.section||r.action||r.kind||'Source section repair')}</summary><pre class="source-detail">${esc(JSON.stringify(r,(key,value)=>key.endsWith('_php')&&typeof value==='number'?php(value):value,2))}</pre></details>`).join('');
$('nepEvidence').textContent=`NEP: ${S.nep_evidence.checked.toLocaleString()} source rows checked; ${S.nep_evidence.status_counts.within_bbox_agreement.toLocaleString()} single-line column/text agreements; ${S.nep_evidence.status_counts.native_row_ambiguity.toLocaleString()} row-identity checks; ${S.nep_evidence.status_counts.nearby_alignment_candidate} nearby alignment candidates; ${S.nep_evidence.status_counts.native_text_review} text/image-review candidates; ${S.nep_evidence.not_checked} unchecked nodes. The ${S.nep_evidence.review_candidates} review candidates are not confirmed amount errors. All 2,552 arithmetic checks balance, including two derived groupings. Arithmetic balance and native-text agreement do not certify every amount against an image.`;
$('method').textContent=D.manifest.matching_method;$('manifest').textContent=JSON.stringify(D.manifest,null,2);
[...new Set(D.paps.map(p=>p.program))].sort().forEach(p=>$('papProgram').add(new Option(p,p)));
function renderPaps(){let rows=D.paps.filter(p=>(!$('papSearch').value||`${p.label} ${p.program}`.toLowerCase().includes($('papSearch').value.toLowerCase()))&&(!$('papProgram').value||p.program===$('papProgram').value)&&(!$('papStatus').value||($('papStatus').value==='coverage_gap'?p.coverage_difference_php!=null&&p.coverage_difference_php!==0:p.comparison_status===$('papStatus').value)));rows.sort((a,b)=>$('papSort').value==='name'?a.label.localeCompare(b.label):Math.abs(($('papSort').value==='gap'?b.coverage_difference_php:b.delta_php)||0)-Math.abs(($('papSort').value==='gap'?a.coverage_difference_php:a.delta_php)||0));$('papCount').textContent=`${rows.length} of ${D.paps.length} PAP and FAP controls · ${S.house_checked_paps} mapped House controls`;$('papRows').innerHTML=rows.map(p=>`<tr><th scope="row"><button data-pap="${esc(p.id)}" aria-expanded="false" aria-controls="detail-${esc(p.id)}">${esc(p.label)}</button><div class="muted">${esc(p.program)} · ${esc(p.id)}</div></th><td>${labels[p.comparison_status]}</td>${[p.nep_printed_php,p.house_printed_php,p.delta_php,p.house_extracted_php,p.coverage_difference_php,p.api_coverage_php].map((x,i)=>cell(x,i===2||i===4)).join('')}</tr><tr id="detail-${esc(p.id)}" class="subrow" hidden><td colspan="8"><p>NEP control ${php(p.nep_printed_php)}, NEP · II-B (retained OCR) p.${p.nep_page}; House control ${php(p.house_printed_php)}; native I-C coverage difference ${delta(p.coverage_difference_php)}. Saved API coverage ${php(p.api_coverage_php)}; source/API gap ${php(p.source_api_gap_php)}. ${p.house_pages.map(hbLink).join(' · ')}</p><p class="muted">Regional amounts use B/M/T with 3 decimals; these are not printed House regional controls.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Regional extraction comparison"><table><thead><tr><th scope="col">Region</th><th scope="col" class="num">House extracted</th><th scope="col" class="num">NEP source</th><th scope="col" class="num">Extracted difference</th></tr></thead><tbody>${p.regions.map(r=>`<tr><th scope="row">${esc(r.region)}</th>${cell(r.house_extracted_php)}${cell(r.nep_source_php)}${cell(r.house_extracted_php-r.nep_source_php,true)}</tr>`).join('')}</tbody></table></div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No PAPs match these filters.</td></tr>';}
$('papRows').addEventListener('click',e=>{const b=e.target.closest('button[data-pap]');if(!b)return;const detail=$('detail-'+b.dataset.pap);detail.hidden=!detail.hidden;b.setAttribute('aria-expanded',String(!detail.hidden));});
$('papSort').addEventListener('change',()=>BudgetDisplay.clear($('papRows').closest('table')));
['papSearch','papProgram','papStatus','papSort'].forEach(id=>$(id).addEventListener(id==='papSearch'?'input':'change',renderPaps));renderPaps();
const statuses={exact_candidate:'Exact title candidate',fuzzy_candidate:'Fuzzy suggestions',ambiguous:'Ambiguous exact key',house_unmatched:'House unmatched',nep_unmatched:'NEP without unique exact pair'};
$('matchSummary').textContent=Object.entries(S.match_counts).map(([k,n])=>`${n.toLocaleString()} ${statuses[k].toLowerCase()}`).join(' · ')+` · ${S.reviewed_pairs} manually certified pairs. Funding partitions are retained inside project totals.`;
const records=D.projects.map((r,i)=>({...r,index:i,search:JSON.stringify([r.house,r.nep,r.candidates]).toLowerCase()}));let pageNumber=0,filtered=records;const pageSize=100;
[...new Set(records.map(r=>(r.house||r.nep).region).filter(Boolean))].sort().forEach(region=>$('projectRegion').add(new Option(region,region)));
function updateOffices(){const region=$('projectRegion').value;const rows=records.filter(r=>!region||(r.house||r.nep).region===region);$('projectOffice').innerHTML='<option value="">All offices</option>'+officeOptions(rows,region).map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('');}
updateOffices();
function evidence(r,stage){if(!r)return '';return `<p><strong>${stage}: ${esc(r.title)}</strong><br>ID ${esc(r.id)} · ${esc(r.pap)} · ${esc(r.region)} · ${esc(r.office)}<br>${stage==='House'?hbLink(r.pdf_page):`NEP · II-B (retained OCR) p.${r.pdf_page}`}<br>Amount ${php(r.amount_php)}<br>Evidence: ${esc(r.evidence)}${r.bbox?`<br>Source bounding box: ${esc(JSON.stringify(r.bbox))}`:''}${Object.keys(r.funding_php).length?`<br>Funding partitions: ${esc(Object.entries(r.funding_php).map(([k,v])=>k+': '+php(v)).join('; '))}`:''}</p>`;}
function renderProjects(){const start=pageNumber*pageSize,rows=filtered.slice(start,start+pageSize);$('previous').disabled=pageNumber===0;$('next').disabled=start+pageSize>=filtered.length;$('projectCount').textContent=filtered.length?`${start+1}–${start+rows.length} of ${filtered.length.toLocaleString()} matching records · ${records.length.toLocaleString()} total records`:`0 matching records · ${records.length.toLocaleString()} total records`;$('projectRows').innerHTML=rows.map(r=>{const primary=r.house||r.nep;return `<tr><th scope="row" class="project-title">${esc(primary.title)}<div class="muted">${esc(primary.pap)}</div></th><td>${statuses[r.status]}${r.status==='exact_candidate'?`<br><span class="badge">${r.delta_php===0?'Exact paired amount':'Paired amount differs'}</span>`:''}</td>${cell(r.house?.amount_php)}<td class="num" data-sort-value="${r.nep?.amount_php??''}">${r.nep?php(r.nep.amount_php):(r.candidates?.length?'See suggestions':'—')}</td>${cell(r.delta_php,true)}<td>${esc(primary.region)}<br>${esc(primary.zone)}${officeLabels(r).map(text=>`<div class="muted">${esc(text)}</div>`).join('')||'<div class="muted">No recorded office</div>'}</td><td class="project-title"><details><summary>Evidence</summary>${r.confidence!=null?`<p>Normalized title similarity ${r.confidence.toFixed(3)}; candidate identity requires review.</p>`:''}${r.reason?`<p>${esc(r.reason)}</p>`:''}${evidence(r.house,'House')}${evidence(r.nep,'NEP')}${(r.candidates||[]).map(c=>`<hr><p>Suggestion similarity ${c.confidence.toFixed(3)}</p>${evidence(c.nep,'NEP')}`).join('')}</details></td></tr>`;}).join('')||'<tr><td colspan="7" class="empty">No project records match these filters.</td></tr>';}
function projectKey(r,column){const p=r.house||r.nep;return [p.title,statuses[r.status],r.house?.amount_php,r.nep?.amount_php,r.delta_php,p.region+' '+p.zone,p.evidence][column];}
function sortProjects(column,direction){filtered.sort((a,b)=>BudgetDisplay.compare(projectKey(a,column),projectKey(b,column),direction));}
function filterProjects(){const q=$('projectSearch').value.toLowerCase().trim();filtered=records.filter(r=>(!q||matchesSearch(r.search,q))&&(!$('projectRegion').value||(r.house||r.nep).region===$('projectRegion').value)&&matchesOffice(r,$('projectOffice').value,$('projectRegion').value)&&(!$('projectStatus').value||r.status===$('projectStatus').value)&&(!$('zoneFilter').value||(r.house||r.nep).zone===$('zoneFilter').value)&&(!$('amountFilter').value||(r.delta_php!=null&&($('amountFilter').value==='equal'?r.delta_php===0:r.delta_php!==0))));const sort=BudgetDisplay.sortState(projectTable);if(sort.column!=null)sortProjects(sort.column,sort.direction);pageNumber=0;renderProjects();}
['projectSearch','projectOffice','projectStatus','amountFilter','zoneFilter'].forEach(id=>$(id).addEventListener(id==='projectSearch'?'input':'change',filterProjects));$('projectRegion').addEventListener('change',()=>{updateOffices();filterProjects();});$('previous').addEventListener('click',()=>{pageNumber--;renderProjects();});$('next').addEventListener('click',()=>{pageNumber++;renderProjects();});BudgetDisplay.register(projectTable,(column,direction)=>{sortProjects(column,direction);pageNumber=0;renderProjects();});renderProjects();

}
